[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "control-remoto"
version = "0.0.0"
description = "Módulo de control remoto para el proyecto"
authors = [ { name = "tpII" } ]
