[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
monitor_filters = 
    colorize          
    esp32_exception_decoder  

board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.psram_type = opi 

build_flags = 
    -DCORE_DEBUG_LEVEL=3          
    -DARDUINO_RUNNING_CORE=1      
    -DARDUINO_EVENT_RUNNING_CORE=1
    
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DOPENCV_DISABLE_EIGEN=1
    -DOPENCV_NO_LAPACK=1

lib_deps = 
    https://github.com/espressif/esp32-camera.git
    bodmer/TJpg_Decoder@^1.0.8
    https://github.com/joachimburket/esp32-opencv.git

upload_speed = 921600
